/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  // {
  //   _id: "Wo5dMEP_BbI",
  //   title: "Awesome Video about Coding",
  //   description:
  //     "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  //   creator: "Soham Shah",
  // },
  // {
  //   _id: "F_Riqjdh2oM",
  //   title: "Neural Networks from Scratch - P.1 Intro and Neuron Code",
  //   creator: "Sentdex",
  //   description:
  //     "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  // },
  {
    _id : "qz0aGYrrlhU",
    title : "HTML Tutorial for Beginners: HTML Crash Course",
    description : "HTML Tutorial for Beginners - Learn HTML for a career in web development. This HTML tutorial teaches you everything you need to get started.",
    category : "HTML5",
    uploaded : "11 Jan, 2021",
    profile : "https://yt3.ggpht.com/tBEPr-zTNXEeae7VZKSZYfiy6azzs9OHowq5ZvogJeHoVtKtEw2PXSwzMBKVR7W0MI7gyND8=s176-c-k-c0x00ffffff-no-rj",
    creator : "Programming with Mosh",
    views : "3,486,169",
    length : "1:09:33",
  },
  {
    _id : "HcOc7P5BMi4",
    title : "HTML Tutorial for Beginners | Complete HTML with Notes & Code",
    description : "HTML Tutorial for Beginners - Learn HTML for a career in web development. This HTML tutorial teaches you everything you need to get started.",
    category : "HTML5",
    uploaded : "22 Mar, 2022",
    profile : "https://yt3.ggpht.com/O12gYmCwBASezJpxddXOj1PEirMgxCGX2gOiJ3plomaK4E0K1hr_iobbQEWz1e4QVMflTmug=s176-c-k-c0x00ffffff-no-rj",
    creator : "Apna College",
    views : "619,352",
    length : "2:05:59",
  },
  {
    _id : "pQN-pnXPaVg",
    title : "HTML Full Course - Build a Website Tutorial",
    description : "Learn the basics of HTML5 and web development in this awesome course for beginners.",
    category : "HTML5",
    uploaded : "18 Sept, 2018",
    profile : "https://yt3.ggpht.com/ytc/AKedOLRyPFojwY3CXV5ks5TwPrt2VifQn-nYNfkgLvVPkw=s176-c-k-c0x00ffffff-no-rj",
    creator : "freeCodeCamp.org",
    views : "5,513,207",
    length : "2:02:31",
  },
  {
    _id : "No8qdcVYiQw",
    title : "Getting started with HTML5",
    description : "Welcome to neogcamp's levelZero journey. You don't know anything about web development? Good, you have come to the right place. Not only you'll learn the language of the web: HTML, you'll learn how to make your site pretty with CSS. When we have learned everything we will put together a decent profile to host your Internet adventures.",
    category : "HTML5",
    uploaded : "22 Nov, 2020",
    profile : "https://yt3.ggpht.com/ytc/AKedOLQnvobEXpzHCxB1g-q2aXbRDzSaznFVHo5OdFML=s176-c-k-c0x00ffffff-no-rj",
    creator : "Tanay Pratap",
    views : "41,122",
    length : "1:45:20",
  },
  {
    _id : "u6_a0d94A1Q",
    title : "Getting started with CSS3",
    description : "Welcome to neogcamp's levelZero journey. You don't know anything about web development? Good, you have come to the right place. Not only you'll learn the language of the web: HTML, you'll learn how to make your site pretty with CSS. When we have learned everything we will put together a decent profile to host your Internet adventures.",
    category : "CSS3",
    uploaded : "22 Nov, 2020",
    profile : "https://yt3.ggpht.com/ytc/AKedOLQnvobEXpzHCxB1g-q2aXbRDzSaznFVHo5OdFML=s176-c-k-c0x00ffffff-no-rj",
    creator : "Tanay Pratap",
    views : "43,373",
    length : "2:17:32",
  },
  {
    _id : "1Rs2ND1ryYc",
    title : "CSS Tutorial - Zero to Hero (Complete Course)",
    description : "Learn CSS in this full course for beginners. CSS, or Cascading Style Sheet, is responsible for the styling and looks of a website. ",
    category : "CSS3",
    uploaded : "16 Oct, 2019",
    profile : "https://yt3.ggpht.com/ytc/AKedOLRyPFojwY3CXV5ks5TwPrt2VifQn-nYNfkgLvVPkw=s176-c-k-c0x00ffffff-no-rj",
    creator : "freeCodeCamp.org",
    views : "2,336,545",
    length : "6:18:37",
  },
  {
    _id : "G3e-cpL7ofc",
    title : "HTML & CSS Full Course - Beginner to Pro (2022)",
    description : "In this full course, we learn how to build websites with HTML and CSS, and get started as a software engineer.",
    category : "CSS3",
    uploaded : "5 Feb, 2022",
    profile : "https://yt3.ggpht.com/ytc/AKedOLSoPzZFsT6n9btrXJ7bYRTnfd1-aYKvre3LScrD=s176-c-k-c0x00ffffff-no-rj",
    creator : "SuperSimpleDev",
    views : "362,916",
    length : "6:31:23",
  },
  {
    _id : "WyxzAU3p8CE",
    title : "CSS Tutorial in Hindi | Complete CSS Course For Beginners to Advanced | Step By Step Tutorial",
    description : "In this tutorial, you will learn CSS. So stay tuned and watch what is CSS and application of CSS.",
    category : "CSS3",
    uploaded : "29 Aug, 2020",
    profile : "https://yt3.ggpht.com/ytc/AKedOLR6yZq47np8hi1ApAfOrRNXQUTnRJBNKMFV6htaKw=s176-c-k-c0x00ffffff-no-rj",
    creator : "Tech Gun",
    views : "1,010,255",
    length : "9:06:50",
  },
  {
    _id : "PkZNo7MFNFg",
    title : "JavaScript Programming - Full Course",
    description : "This complete 134-part JavaScript tutorial for beginners will teach you everything you need to know to get started with the JavaScript programming language.",
    category : "Javascript",
    uploaded : "10 Dec, 2018",
    profile : "https://yt3.ggpht.com/ytc/AKedOLRyPFojwY3CXV5ks5TwPrt2VifQn-nYNfkgLvVPkw=s176-c-k-c0x00ffffff-no-rj",
    creator : "freeCodeCamp.org",
    views : "9,177,576",
    length : "3:26:42",
  },
  {
    _id : "chx9Rs41W6g",
    title : "JavaScript | Beginning to Mastery Complete Tutorial (Part 1)",
    description : "Complete modern javascript/es6 tutorial in Hindi (2021)",
    category : "Javascript",
    uploaded : "9 Oct, 2021",
    profile : "https://yt3.ggpht.com/ytc/AKedOLRq3jU1DPj1kbW2-B53lHdmiAHYb87EZ0PoZ9oPyQ=s176-c-k-c0x00ffffff-no-rj",
    creator : "Harshit vashisth",
    views : "574,913",
    length : "11:08:32",
  },
  {
    _id : "_zPNLidkNYk",
    title : "JavaScript Full Course 2022 | JavaScript Tutorial For Beginners | JavaScript Developer | Simplilearn",
    description : "This JavaScript Full Course video will help you become proficient in JavaScript. At the end of the video, you will have a strong understanding of the concepts required to build complex JS applications.",
    category : "Javascript",
    uploaded : "16 Dec, 2021",
    profile : "https://yt3.ggpht.com/ytc/AKedOLTaNnIZrEVNHk-OgfTRlO1n2aeAZ657f5FrG-5EaA=s176-c-k-c0x00ffffff-no-rj",
    creator : "Simplilearn",
    views : "82,180",
    length : "11:32:26",
  },
  {
    _id : "8dWL3wF_OMw",
    title : "JavaScript Full Course 🌐 -Learn to code today-【𝙁𝙧𝙚𝙚】",
    description : "This JavaScript Full Course video will help you become proficient in JavaScript. At the end of the video, you will have a strong understanding of the concepts required to build complex JS applications.",
    category : "Javascript",
    uploaded : "5 Mar, 2022",
    profile : "https://yt3.ggpht.com/ytc/AKedOLT4INVhTDpREf95PcEwVNnZQCowP-h-y76N71zOTw=s176-c-k-c0x00ffffff-no-rj",
    creator : "Bro Code",
    views : "200,675",
    length : "8:00:00",
  },
  {
    _id : "Ke90Tje7VS0",
    title : "React JS - React Tutorial for Beginners",
    description : "React JS Tutorial - Get up & running with React JS: the most popular JavaScript library in the world!",
    category : "React JS",
    uploaded : "16 Jul, 2018",
    profile : "https://yt3.ggpht.com/tBEPr-zTNXEeae7VZKSZYfiy6azzs9OHowq5ZvogJeHoVtKtEw2PXSwzMBKVR7W0MI7gyND8=s176-c-k-c0x00ffffff-no-rj",
    creator : "Programming with Mosh",
    views : "4,749,929",
    length : "2:25:26",
  },
  {
    _id : "bMknfKXIFA8",
    title : "React Course - Beginner's Tutorial for React JavaScript Library [2022]",
    description : "Learn React by building eight real-world projects and solving 140+ coding challenges.",
    category : "React JS",
    uploaded : "11 Jan, 2021",
    profile : "https://yt3.ggpht.com/ytc/AKedOLRyPFojwY3CXV5ks5TwPrt2VifQn-nYNfkgLvVPkw=s176-c-k-c0x00ffffff-no-rj",
    creator : "freeCodeCamp.org",
    views : "788,564",
    length : "11:55:27",
  },
  {
    _id : "0riHps91AzE",
    title : "Learn React JS with Project in 2 Hours | React Tutorial for Beginners | React Project Crash Course",
    description : "This video is a complete React Crash Course for beginners. The video covers different React Topics and implementation in one single project. The video showcase the React concepts and their use in practical project.",
    category : "React JS",
    uploaded : "15 May, 2021",
    profile : "https://yt3.ggpht.com/ytc/AKedOLQ9EF8YtmsiSNwSKazGG2I6TZYArvYQM0_zShHvQg=s176-c-k-c0x00ffffff-no-rj",
    creator : "Dipesh Malvia",
    views : "598,114",
    length : "1:56:17",
  },
  {
    _id : "gY5sGvq-8h8",
    title : "ReactJS Tutorial for Beginners | Learn React in 2.5 Hours | Part 1",
    description : "React JS Tutorial - Get up & running with React JS: the most popular JavaScript library in the world!",
    category : "React JS",
    uploaded : "17 Dec, 2021",
    profile : "https://yt3.ggpht.com/O12gYmCwBASezJpxddXOj1PEirMgxCGX2gOiJ3plomaK4E0K1hr_iobbQEWz1e4QVMflTmug=s176-c-k-c0x00ffffff-no-rj",
    creator : "Apna College",
    views : "219,813",
    length : "2:25:43",
  }
];
